## SET UP THE ENVIRONMENT

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

### Import data set

In [4]:
gss=pd.read_csv("GSSsubset.csv")
gss.head()

   id     sex       degree    income   marital   age  height  weight  hrswrk
0   1    MALE     BACHELOR  60967.50  DIVORCED  53.0    72.0   190.0    60.0
1   2  FEMALE     BACHELOR  60967.50   MARRIED  26.0    60.0    97.0    40.0
2   4  FEMALE     BACHELOR  10161.25   MARRIED  56.0    68.0   160.0    20.0
3  14  FEMALE  HIGH SCHOOL  17551.25   MARRIED  40.0    65.0   156.0    37.0
4  16    MALE  HIGH SCHOOL  17551.25   MARRIED  56.0     NaN   210.0     6.0

### filtering rows

In [8]:
gss_marital=gss.query("marital=='MARRIED'")
gss_marital.head()

   id     sex          degree    income  marital   age  height  weight  hrswrk
1   2  FEMALE        BACHELOR  60967.50  MARRIED  26.0    60.0    97.0    40.0
2   4  FEMALE        BACHELOR  10161.25  MARRIED  56.0    68.0   160.0    20.0
3  14  FEMALE     HIGH SCHOOL  17551.25  MARRIED  40.0    65.0   156.0    37.0
4  16    MALE     HIGH SCHOOL  17551.25  MARRIED  56.0     NaN   210.0     6.0
5  19    MALE  LT HIGH SCHOOL  15703.75  MARRIED  51.0    68.0   170.0     NaN

In [9]:
gss_marital

,id,sex,degree,income,marital,age,height,weight,hrswrk
1,2,FEMALE,BACHELOR,60967.50,MARRIED,26.0,60.0,97.0,40.0
2,4,FEMALE,BACHELOR,10161.25,MARRIED,56.0,68.0,160.0,20.0
3,14,FEMALE,HIGH SCHOOL,17551.25,MARRIED,40.0,65.0,156.0,37.0
4,16,MALE,HIGH SCHOOL,17551.25,MARRIED,56.0,NaN,210.0,6.0
5,19,MALE,LT HIGH SCHOOL,15703.75,MARRIED,51.0,68.0,170.0,NaN
...,...,...,...,...,...,...,...,...,...
984,2523,MALE,BACHELOR,24017.50,MARRIED,54.0,72.0,195.0,40.0
985,2524,MALE,BACHELOR,33255.00,MARRIED,49.0,70.0,195.0,40.0
986,2525,FEMALE,BACHELOR,33255.00,MARRIED,53.0,64.0,150.0,40.0
987,2526,MALE,BACHELOR,40645.00,MARRIED,52.0,72.0,200.0,50.0
988,2530,MALE,HIGH SCHOOL,33255.00,MARRIED,62.0,71.0,215.0,48.0

## Filter rows with age> 20

In [10]:
gss_age=gss.query("age>=70")
gss_age

,id,sex,degree,income,marital,age,height,weight,hrswrk
56,151,FEMALE,BACHELOR,10161.25,DIVORCED,74.0,62.0,137.0,24.0
69,180,FEMALE,GRADUATE,8313.75,DIVORCED,71.0,62.0,102.0,40.0
98,252,MALE,BACHELOR,40645.00,MARRIED,72.0,65.0,142.0,48.0
130,351,MALE,GRADUATE,8313.75,MARRIED,70.0,71.0,195.0,15.0
156,405,MALE,BACHELOR,88680.00,MARRIED,70.0,70.0,180.0,45.0
160,412,FEMALE,HIGH SCHOOL,17551.25,NEVER MARRIED,72.0,66.0,160.0,37.0
173,445,MALE,HIGH SCHOOL,6651.00,WIDOWED,78.0,69.0,210.0,23.0
227,585,FEMALE,HIGH SCHOOL,13856.25,MARRIED,70.0,62.0,130.0,36.0
293,767,MALE,HIGH SCHOOL,40645.00,MARRIED,75.0,71.0,205.0,40.0
297,773,MALE,GRADUATE,27712.50,NEVER MARRIED,74.0,73.0,195.0,20.0
523,1325,MALE,HIGH SCHOOL,1478.00,MARRIED,76.0,70.0,150.0,4.0
546,1376,FEMALE,HIGH SCHOOL,8313.75,WIDOWED,75.0,62.0,120.0,28.0
554,1394,FEMALE,LT HIGH SCHOOL,24017.50,WIDOWED,71.0,65.0,142.0,35.0
591,1500,MALE,LT HIGH SCHOOL,10161.25,MARRIED,73.0,68.0,251.0,29.0
654,1682,MALE,HIGH SCHOOL,60967.50,NEVER MARRIED,72.0,72.0,220.0,44.0
702,1810,FEMALE,HIGH SCHOOL,40645.00,MARRIED,77.0,58.0,158.0,20.0
703,1813,FEMALE,BACHELOR,15703.75,NEVER MARRIED,74.0,65.0,145.0,4.0
717,1850,FEMALE,HIGH SCHOOL,4064.50,MARRIED,72.0,63.0,200.0,15.0
838,2163,MALE,HIGH SCHOOL,15703.75,MARRIED,79.0,65.0,130.0,30.0
886,2268,FEMALE,GRADUATE,49882.50,DIVORCED,70.0,70.0,226.0,32.0
914,2350,FEMALE,HIGH SCHOOL,369.50,WIDOWED,74.0,61.0,124.0,30.0
922,2366,MALE,BACHELOR,20322.50,WIDOWED,76.0,63.0,105.0,8.0
960,2455,MALE,JUNIOR COLLEGE,15703.75,MARRIED,71.0,72.0,165.0,70.0
961,2457,MALE,HIGH SCHOOL,12008.75,MARRIED,74.0,68.0,185.0,40.0
993,2538,FEMALE,HIGH SCHOOL,15703.75,WIDOWED,71.0,63.0,140.0,48.0

## SELECTING COLUMNS

In [11]:
gss_selected=gss.loc[:,["sex","income","marital","age"]]
gss_selected

        sex    income        marital   age
0      MALE  60967.50       DIVORCED  53.0
1    FEMALE  60967.50        MARRIED  26.0
2    FEMALE  10161.25        MARRIED  56.0
3    FEMALE  17551.25        MARRIED  40.0
4      MALE  17551.25        MARRIED  56.0
..      ...       ...            ...   ...
989    MALE   1478.00  NEVER MARRIED  40.0
990    MALE  33255.00       DIVORCED  56.0
991    MALE   8313.75  NEVER MARRIED  24.0
992    MALE  27712.50  NEVER MARRIED  27.0
993  FEMALE  15703.75        WIDOWED  71.0

[994 rows x 4 columns]

## SORTING DATA

In [13]:
gss_income_arranged=gss.sort_values(by="income",ascending=False)
gss_income_arranged

,id,sex,degree,income,marital,age,height,weight,hrswrk
967,2474,FEMALE,BACHELOR,158656.952,DIVORCED,38.0,65.0,145.0,45.0
27,68,MALE,GRADUATE,158656.952,DIVORCED,57.0,71.0,180.0,70.0
953,2428,MALE,GRADUATE,158656.952,MARRIED,67.0,70.0,183.0,75.0
895,2288,MALE,GRADUATE,158656.952,DIVORCED,62.0,71.0,220.0,50.0
47,128,MALE,GRADUATE,158656.952,MARRIED,38.0,68.0,160.0,60.0
...,...,...,...,...,...,...,...,...,...
878,2246,FEMALE,HIGH SCHOOL,369.500,MARRIED,47.0,70.0,168.0,NaN
937,2395,MALE,HIGH SCHOOL,369.500,DIVORCED,20.0,73.0,185.0,24.0
880,2256,MALE,HIGH SCHOOL,369.500,NEVER MARRIED,44.0,71.0,150.0,40.0
914,2350,FEMALE,HIGH SCHOOL,369.500,WIDOWED,74.0,61.0,124.0,30.0
171,440,FEMALE,GRADUATE,369.500,NEVER MARRIED,25.0,62.0,138.0,10.0

## SUMMARIZING DATA

In [14]:
gss_summarized=gss.groupby("sex")["income"].mean().reset_index()
gss_summarized

      sex        income
0  FEMALE  27300.446119
1    MALE  46095.814166

## Sorting grouped results

In [17]:
gss_summarized=gss.groupby("degree")["income"].mean().reset_index().sort_values(by="income",ascending=False)
gss_summarized

           degree        income
1        GRADUATE  68457.773552
0        BACHELOR  47738.621187
3  JUNIOR COLLEGE  30580.141304
2     HIGH SCHOOL  28309.892098
4  LT HIGH SCHOOL  18412.616883

In [18]:
gss_summarized=gss.groupby("marital")["income"].mean().reset_index().sort_values(by="income",ascending=False)
gss_summarized

         marital        income
1        MARRIED  43838.108058
0       DIVORCED  39881.177721
3      SEPARATED  25903.775730
2  NEVER MARRIED  25828.277524
4        WIDOWED  23827.618056

In [19]:
gss_summarized=gss.groupby("age")["income"].mean().reset_index().sort_values(by="income",ascending=False)
gss_summarized

     age        income
48  67.0  71206.692333
47  66.0  68577.613000
49  68.0  67973.567333
41  60.0  65234.895619
50  69.0  60217.675500
..   ...           ...
54  73.0  10161.250000
0   19.0   8744.833333
59  78.0   6651.000000
2   21.0   6137.805556
1   20.0   5665.666667

[61 rows x 2 columns]

## CHAINING OPERATIONS

#### 1. Filter for respondents over 40 years old
#### 2. Select only the columns for degree, income and sex
#### 3. Create a new column "income category" that labels income as "high" if over 50000 otherwise "low"
#### 4. Sort the results by income in descending order (Highest incomes first)

In [22]:
gss_processed=(
    gss.query("age>40")
    .loc[:,["degree", "income", "sex"]]
    .assign(income_category=lambda x:np.where(x["income"]>50000,"High","Low")).sort_values(by="income",ascending=False))
gss_processed

          degree      income     sex income_category
953     GRADUATE  158656.952    MALE            High
86   HIGH SCHOOL  158656.952    MALE            High
50      GRADUATE  158656.952    MALE            High
265     GRADUATE  158656.952    MALE            High
198     BACHELOR  158656.952    MALE            High
..           ...         ...     ...             ...
64      BACHELOR     369.500  FEMALE             Low
379  HIGH SCHOOL     369.500    MALE             Low
914  HIGH SCHOOL     369.500  FEMALE             Low
266     BACHELOR     369.500  FEMALE             Low
246     BACHELOR     369.500  FEMALE             Low

[581 rows x 4 columns]

## Dataset reorganization

In [24]:
gss.iloc[9,1]

'MALE'

In [25]:
gss.iloc[:,0]

0         1
1         2
2         4
3        14
4        16
       ...
989    2531
990    2535
991    2536
992    2537
993    2538
Name: id, Length: 994, dtype: int64

In [26]:
gss.iloc[0,:]

id                1
sex            MALE
degree     BACHELOR
income      60967.5
marital    DIVORCED
age            53.0
height         72.0
weight        190.0
hrswrk         60.0
Name: 0, dtype: object

## SUBSETTING BASED ON CONDITIONS

In [27]:
gss[gss["income"]>50000]

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1,MALE,BACHELOR,60967.500,DIVORCED,53.0,72.0,190.0,60.0
1,2,FEMALE,BACHELOR,60967.500,MARRIED,26.0,60.0,97.0,40.0
8,28,MALE,BACHELOR,73900.000,MARRIED,57.0,71.0,225.0,40.0
12,40,MALE,BACHELOR,73900.000,MARRIED,35.0,NaN,200.0,50.0
14,45,FEMALE,BACHELOR,88680.000,SEPARATED,50.0,67.0,188.0,60.0
...,...,...,...,...,...,...,...,...,...
932,2383,MALE,HIGH SCHOOL,60967.500,MARRIED,49.0,68.0,178.0,45.0
951,2419,MALE,LT HIGH SCHOOL,60967.500,MARRIED,48.0,70.0,205.0,65.0
952,2423,MALE,BACHELOR,60967.500,MARRIED,30.0,67.0,195.0,48.0
953,2428,MALE,GRADUATE,158656.952,MARRIED,67.0,70.0,183.0,75.0
967,2474,FEMALE,BACHELOR,158656.952,DIVORCED,38.0,65.0,145.0,45.0

In [30]:
gss[gss["degree"]=="GRADUATE"]

,id,sex,degree,income,marital,age,height,weight,hrswrk
18,49,FEMALE,GRADUATE,88680.000,MARRIED,32.0,66.0,160.0,40.0
20,51,FEMALE,GRADUATE,33255.000,MARRIED,52.0,NaN,143.0,40.0
25,61,MALE,GRADUATE,15703.750,NEVER MARRIED,51.0,70.0,190.0,14.0
26,64,FEMALE,GRADUATE,60967.500,NEVER MARRIED,47.0,64.0,NaN,40.0
27,68,MALE,GRADUATE,158656.952,DIVORCED,57.0,71.0,180.0,70.0
...,...,...,...,...,...,...,...,...,...
927,2374,MALE,GRADUATE,158656.952,DIVORCED,40.0,70.0,290.0,89.0
940,2400,MALE,GRADUATE,33255.000,MARRIED,38.0,69.0,170.0,50.0
942,2403,FEMALE,GRADUATE,33255.000,MARRIED,54.0,62.0,130.0,46.0
953,2428,MALE,GRADUATE,158656.952,MARRIED,67.0,70.0,183.0,75.0
979,2517,MALE,GRADUATE,40645.000,MARRIED,65.0,68.0,165.0,40.0

In [31]:
gss[gss["marital"]=="DIVORCED"]

,id,sex,degree,income,marital,age,height,weight,hrswrk
0,1,MALE,BACHELOR,60967.50,DIVORCED,53.0,72.0,190.0,60.0
6,21,FEMALE,HIGH SCHOOL,17551.25,DIVORCED,30.0,62.0,115.0,NaN
9,30,MALE,BACHELOR,33255.00,DIVORCED,54.0,71.0,165.0,40.0
10,32,FEMALE,BACHELOR,33255.00,DIVORCED,61.0,64.0,128.0,40.0
11,38,MALE,HIGH SCHOOL,33255.00,DIVORCED,31.0,67.0,150.0,NaN
...,...,...,...,...,...,...,...,...,...
969,2480,FEMALE,HIGH SCHOOL,20322.50,DIVORCED,55.0,65.0,208.0,40.0
970,2482,FEMALE,HIGH SCHOOL,17551.25,DIVORCED,53.0,70.0,170.0,20.0
974,2500,MALE,HIGH SCHOOL,20322.50,DIVORCED,53.0,72.0,200.0,60.0
983,2522,FEMALE,HIGH SCHOOL,24017.50,DIVORCED,49.0,67.0,200.0,50.0
990,2535,MALE,HIGH SCHOOL,33255.00,DIVORCED,56.0,72.0,195.0,46.0

## SUMMARY REPORT

In [34]:
gss.groupby("degree")["income"].agg(["mean","min","max","median","std"])

                        mean     min         max    median           std
degree
BACHELOR        47738.621187   369.5  158656.952  40645.00  38036.482608
GRADUATE        68457.773552   369.5  158656.952  49882.50  47526.992948
HIGH SCHOOL     28309.892098   369.5  158656.952  24017.50  26671.333894
JUNIOR COLLEGE  30580.141304  1478.0  103460.000  27712.50  20292.993851
LT HIGH SCHOOL  18412.616883  1478.0   73900.000  15703.75  13324.116851

In [35]:
gss.groupby(["sex", "degree"])["income"].mean()

sex     degree
FEMALE  BACHELOR          34269.353010
        GRADUATE          52381.502655
        HIGH SCHOOL       21630.135693
        JUNIOR COLLEGE    22180.077273
        LT HIGH SCHOOL    11350.578125
MALE    BACHELOR          60334.881241
        GRADUATE          82374.545373
        HIGH SCHOOL       34749.177272
        JUNIOR COLLEGE    43066.722973
        LT HIGH SCHOOL    23434.511111
Name: income, dtype: float64

In [36]:
gss.groupby(["marital", "degree"])["income"].mean()

marital        degree
DIVORCED       BACHELOR          46020.998286
               GRADUATE          82238.971684
               HIGH SCHOOL       31799.907570
               JUNIOR COLLEGE    38593.302632
               LT HIGH SCHOOL    24443.846154
MARRIED        BACHELOR          54804.048164
               GRADUATE          71705.055013
               HIGH SCHOOL       34815.932837
               JUNIOR COLLEGE    29082.353659
               LT HIGH SCHOOL    18418.153846
NEVER MARRIED  BACHELOR          33894.519231
               GRADUATE          48534.056160
               HIGH SCHOOL       20047.210265
               JUNIOR COLLEGE    27605.913462
               LT HIGH SCHOOL    15137.183333
SEPARATED      BACHELOR          88680.000000
               GRADUATE          62954.140400
               HIGH SCHOOL       17126.325000
               JUNIOR COLLEGE    24017.500000
               LT HIGH SCHOOL    15395.833333
WIDOWED        BACHELOR          25249.166667
               GRADUATE          88680.000000
               HIGH SCHOOL       21061.500000
               JUNIOR COLLEGE    49882.500000
               LT HIGH SCHOOL    15565.187500
Name: income, dtype: float64

## Hand-on Exercise

In [38]:
import pandas as pd
mtcars=pd.read_csv("mtcars.csv")
mtcars.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,36945.0,33337.0,3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820.0,21761.0,2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,26990.0,24647.0,2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,33195.0,30299.0,3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755.0,39014.0,3.5,6.0,225,18,24,3880,115,197

In [46]:
mtcars_Weight=mtcars.query("Weight>=3.5")
mtcars_Weight

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,36945.0,33337.0,3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820.0,21761.0,2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,26990.0,24647.0,2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,33195.0,30299.0,3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755.0,39014.0,3.5,6.0,225,18,24,3880,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565.0,38203.0,2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565.0,40083.0,2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210.0,42573.0,2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,26135.0,24641.0,1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,35145.0,33112.0,2.5,5.0,208,20,27,3823,109,186

In [49]:
mtcars_selected=mtcars.loc[:,["MPG_City","Cylinders","Horsepower"]]
mtcars_selected

     MPG_City  Cylinders  Horsepower
0          17        6.0         265
1          24        4.0         200
2          22        4.0         200
3          20        6.0         270
4          18        6.0         225
..        ...        ...         ...
423        21        5.0         197
424        20        5.0         242
425        19        6.0         268
426        22        4.0         170
427        20        5.0         208

[428 rows x 3 columns]

In [50]:
mtcars_mutated=mtcars.assign(Horsepower_categories=np.where(mtcars["Horsepower"]>150,"High","Low"))
mtcars_mutated.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length,Horsepower_categories
0,Acura,MDX,SUV,Asia,All,36945.0,33337.0,3.5,6.0,265,17,23,4451,106,189,High
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820.0,21761.0,2.0,4.0,200,24,31,2778,101,172,High
2,Acura,TSX 4dr,Sedan,Asia,Front,26990.0,24647.0,2.4,4.0,200,22,29,3230,105,183,High
3,Acura,TL 4dr,Sedan,Asia,Front,33195.0,30299.0,3.2,6.0,270,20,28,3575,108,186,High
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755.0,39014.0,3.5,6.0,225,18,24,3880,115,197,High

In [53]:
mtcars_processed=mtcars.query("Weight>=3.5").loc[:,["MPG_City","Cylinders","Horsepower"]].assign(Horsepower_categories=np.where(mtcars["Horsepower"]>150,"High","Low"))
mtcars_processed

     MPG_City  Cylinders  Horsepower Horsepower_categories
0          17        6.0         265                  High
1          24        4.0         200                  High
2          22        4.0         200                  High
3          20        6.0         270                  High
4          18        6.0         225                  High
..        ...        ...         ...                   ...
423        21        5.0         197                  High
424        20        5.0         242                  High
425        19        6.0         268                  High
426        22        4.0         170                  High
427        20        5.0         208                  High

[428 rows x 4 columns]